### ISSUE TITLE
Research Firebase pricing

### ISSUE THREAD

**Issue by clue4** [sandboxnu/ScoutTrek-Backend#8]
We are considering switching to Firebase for authentication as it has a lot of features that would make things a lot easier. However, pricing may be an issue, given how we want ScoutTrek to be able to scale.

**Specs**
Essentially, what we want to know is just how expensive Firebase can get -- especially if ScoutTrek were to have many, many users

**Comment by jaron-cui** [comment]
Firebase has a generous 'free' plan that would likely be sufficient for development. In terms of larger-scale use, it is slightly more expensive than the alternatives (MongoDB, AWS) but still quite affordable.
The use case seems to be a good fit, since Firebase's main advantage is being comparably fast due to its cloud integration.
Additionally, we can set up alerts and spending limits to avoid unintentionally accumulating expenses.
Google provides a comprehensive price calculator we can use to determine costs for projections:
https://firebase.google.com/pricing
